query LiveStoreContext {
  shop {
    name
    myshopifyDomain
  }
  collections(first: 250) {
    nodes {
      id
      title
      handle
      productsCount {
        count
      }
      ruleSet {
        appliedDisjunctively
        rules {
          column
          relation
          condition
        }
      }
    }
  }
  productTags(first: 250) {
    nodes
  }
  products(first: 250, sortKey: UPDATED_AT, reverse: true) {
    nodes {
      handle
      title
      vendor
      productType
      tags
      status
      updatedAt
      productCategory { productTaxonomyNode { id fullName } }
    }
  }
}
